name: manager_dashboard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.40.0
  path_provider: ^2.0.15
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.1
  firebase_database: ^10.3.1
  excel: ^2.0.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  
  

flutter:
  uses-material-design: true